export const rapidApiKey = '176f43d985msh6109d44bae34c0ap160fcejsn1f7fbf7d1608';
export const sliderImages = [
    require('../assets/images/slide1.png'),
    require('../assets/images/slide3.png'),
    require('../assets/images/slide2.png'),
    require('../assets/images/slide4.png'),
    require('../assets/images/slide5.png'),
];

export const bodyParts = [
    {
        name: 'back',
        image: require('../assets/images/back.png'),
    },
    {
        name: 'cardio',
        image: require('../assets/images/cardio.png'),
    },

    {
        name: 'lower arms',
        image: require('../assets/images/lowerArms.png'),
    },
    {
        name: 'lower legs',
        image: require('../assets/images/lowerLegs.png'),
    },
    {
        name: 'chest',
        image: require('../assets/images/chest.png'),
    },
    {
        name: 'neck',
        image: require('../assets/images/neck.png'),
    },
    {
        name: 'shoulders',
        image: require('../assets/images/shoulders.png'),
    },
    {
        name: 'upper arms',
        image: require('../assets/images/upperArms.png'),
    },
    {
        name: 'upper legs',
        image: require('../assets/images/upperLegs.png'),
    },
    {
        name: 'waist',
        image: require('../assets/images/waist.png'),
    },
];

export const demoExercises = [
    {
        bodyPart: 'waist',
        equipment: 'body weight',
        gifUrl: 'https://v2.exercisedb.io/image/14fZGdkY3j6KTt',
        id: '0001',
        name: '3/4 sit-up',
        target: 'abs',
        secondaryMuscles: ['hip flexors', 'lower back'],
        instructions: [
            'Lie flat on your back with your knees bent and feet flat on the ground.',
            'Place your hands behind your head with your elbows pointing outwards.',
            'Engaging your abs, slowly lift your upper body off the ground, curling forward until your torso is at a 45-degree angle.',
            'Pause for a moment at the top, then slowly lower your upper body back down to the starting position.',
            'Repeat for the desired number of repetitions.',
        ],
    },
    {
        bodyPart: 'waist',
        equipment: 'body weight',
        gifUrl: 'https://v2.exercisedb.io/image/oNKKDBgcQqXaig',
        id: '0002',
        name: '45° side bend',
        target: 'abs',
        secondaryMuscles: ['obliques'],
        instructions: [
            'Stand with your feet shoulder-width apart and your arms extended straight down by your sides.',
            'Keeping your back straight and your core engaged, slowly bend your torso to one side, lowering your hand towards your knee.',
            'Pause for a moment at the bottom, then slowly return to the starting position.',
            'Repeat on the other side.',
            'Continue alternating sides for the desired number of repetitions.',
        ],
    },
    {
        bodyPart: 'waist',
        equipment: 'body weight',
        gifUrl: 'https://v2.exercisedb.io/image/pYEB75tMhsS4S9',
        id: '0003',
        name: 'air bike',
        target: 'abs',
        secondaryMuscles: ['hip flexors'],
        instructions: [
            'Lie flat on your back with your hands placed behind your head.',
            'Lift your legs off the ground and bend your knees at a 90-degree angle.',
            'Bring your right elbow towards your left knee while simultaneously straightening your right leg.',
            'Return to the starting position and repeat the movement on the opposite side, bringing your left elbow towards your right knee while straightening your left leg.',
            'Continue alternating sides in a pedaling motion for the desired number of repetitions.',
        ],
    },
    {
        bodyPart: 'upper legs',
        equipment: 'body weight',
        gifUrl: 'https://v2.exercisedb.io/image/gcKy2H8c6SYEt4',
        id: '1512',
        name: 'all fours squad stretch',
        target: 'quads',
        secondaryMuscles: ['hamstrings', 'glutes'],
        instructions: [
            'Start on all fours with your hands directly under your shoulders and your knees directly under your hips.',
            'Extend one leg straight back, keeping your knee bent and your foot flexed.',
            'Slowly lower your hips towards the ground, feeling a stretch in your quads.',
            'Hold this position for 20-30 seconds.',
            'Switch legs and repeat the stretch on the other side.',
        ],
    },
    {
        bodyPart: 'waist',
        equipment: 'body weight',
        gifUrl: 'https://v2.exercisedb.io/image/42s8CJeMhkYMwT',
        id: '0006',
        name: 'alternate heel touchers',
        target: 'abs',
        secondaryMuscles: ['obliques'],
        instructions: [
            'Lie flat on your back with your knees bent and feet flat on the ground.',
            'Extend your arms straight out to the sides, parallel to the ground.',
            'Engaging your abs, lift your shoulders off the ground and reach your right hand towards your right heel.',
            'Return to the starting position and repeat on the left side, reaching your left hand towards your left heel.',
            'Continue alternating sides for the desired number of repetitions.',
        ],
    },
    {
        bodyPart: 'back',
        equipment: 'cable',
        gifUrl: 'https://v2.exercisedb.io/image/RyL1P5Mzo2npY6',
        id: '0007',
        name: 'alternate lateral pulldown',
        target: 'lats',
        secondaryMuscles: ['biceps', 'rhomboids'],
        instructions: [
            'Sit on the cable machine with your back straight and feet flat on the ground.',
            'Grasp the handles with an overhand grip, slightly wider than shoulder-width apart.',
            'Lean back slightly and pull the handles towards your chest, squeezing your shoulder blades together.',
            'Pause for a moment at the peak of the movement, then slowly release the handles back to the starting position.',
            'Repeat for the desired number of repetitions.',
        ],
    },
    {
        bodyPart: 'lower legs',
        equipment: 'body weight',
        gifUrl: 'https://v2.exercisedb.io/image/RsuRVfTWWutpRA',
        id: '1368',
        name: 'ankle circles',
        target: 'calves',
        secondaryMuscles: ['ankle stabilizers'],
        instructions: [
            'Sit on the ground with your legs extended in front of you.',
            'Lift one leg off the ground and rotate your ankle in a circular motion.',
            'Perform the desired number of circles in one direction, then switch to the other direction.',
            'Repeat with the other leg.',
        ],
    },
    {
        bodyPart: 'back',
        equipment: 'body weight',
        gifUrl: 'https://v2.exercisedb.io/image/Wodn1valM4e8uA',
        id: '3293',
        name: 'archer pull up',
        target: 'lats',
        secondaryMuscles: ['biceps', 'forearms'],
        instructions: [
            'Start by hanging from a pull-up bar with an overhand grip, slightly wider than shoulder-width apart.',
            'Engage your core and pull your shoulder blades down and back.',
            'As you pull yourself up, bend one arm and bring your elbow towards your side, while keeping the other arm straight.',
            'Continue pulling until your chin is above the bar and your bent arm is fully flexed.',
            'Lower yourself back down with control, straightening the bent arm and repeating the movement on the other side.',
            'Alternate sides with each repetition.',
        ],
    },
    {
        bodyPart: 'chest',
        equipment: 'body weight',
        gifUrl: 'https://v2.exercisedb.io/image/BQ-PsjTlAyrwfE',
        id: '3294',
        name: 'archer push up',
        target: 'pectorals',
        secondaryMuscles: ['triceps', 'shoulders', 'core'],
        instructions: [
            'Start in a push-up position with your hands slightly wider than shoulder-width apart.',
            'Extend one arm straight out to the side, parallel to the ground.',
            'Lower your body by bending your elbows, keeping your back straight and core engaged.',
            'Push back up to the starting position.',
            'Repeat on the other side, extending the opposite arm out to the side.',
            'Continue alternating sides for the desired number of repetitions.',
        ],
    },
    {
        bodyPart: 'waist',
        equipment: 'body weight',
        gifUrl: 'https://v2.exercisedb.io/image/TYzfLR7hW3zjPL',
        id: '2355',
        name: 'arm slingers hanging bent knee legs',
        target: 'abs',
        secondaryMuscles: ['shoulders', 'back'],
        instructions: [
            'Hang from a pull-up bar with your arms fully extended and your knees bent at a 90-degree angle.',
            'Engage your core and lift your knees towards your chest, bringing them as close to your elbows as possible.',
            'Slowly lower your legs back down to the starting position.',
            'Repeat for the desired number of repetitions.',
        ],
    },
];
